version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 010928179293.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - IMAGE_TAG=$(date +%Y%m%d%H%M%S)  # Generate a unique image tag
      - echo "Building the Docker image..."
      - docker build -t 010928179293.dkr.ecr.us-east-1.amazonaws.com/akash2:$IMAGE_TAG .
      - echo "Pushing the Docker image..."
      - docker push 010928179293.dkr.ecr.us-east-1.amazonaws.com/akash2:$IMAGE_TAG
      - echo Writing image definitions file... 
      # Give your container name
      - DOCKER_CONTAINER_NAME=sample
      - printf '[{"name":"%s","imageUri":"%s"}]' $DOCKER_CONTAINER_NAME 010928179293.dkr.ecr.us-east-1.amazonaws.com/akash2:$IMAGE_TAG > imagedefinitions.json
      - echo $DOCKER_CONTAINER_NAME
      - echo printing imagedefinitions.json
      - cat imagedefinitions.json

  post_build:
    commands:
      - echo "Build completed. Image pushed to ECR."

artifacts:
  files:
    - imagedefinitions.json
